### ISSUE TITLE
The "one-by-one" configuration could be modernized a bit

### ISSUE THREAD

**Issue by ondrejmirtes** [canvural/larastan-strict-rules#152]
Hello Can,
awesome package! I have a suggestion for you: I don't really like when people copy-paste a class name from a package and put it in their own phpstan.neon. Because it ties the maintainer's hands - you can't change the class name, you can't add constructor arguments to it.

Instead of this:

```neon
services:
    -
        class: Vural\LarastanStrictRules\Rules\NoDynamicWhereRule
        tags:
            - phpstan.rules.rule
    -
        class: Vural\LarastanStrictRules\Rules\NoFacadeRule
        tags:
            - phpstan.rules.rule
```

You could provide parameters so that this is possible instead:

```neon
parameters:
    larastanStrictRules:
        noDynamicWhere: true
        noFacade: true
```

See how it's done with `conditionalTags` in phpstan-strict-rules: https://github.com/phpstan/phpstan-strict-rules/blob/5c143aa605bbf392a90630773618eeaeeac7a49b/rules.neon#L50-L52

**Comment by canvural** [comment]
Hi,

That's an awesome idea! Thank you for the tip.
