### ISSUE TITLE
NoDynamicWhereRule is restricting the usage of wherePivot 

### ISSUE THREAD

**Issue by jeremynikolic** [canvural/larastan-strict-rules#91]
Hire there 👋 ,

In one of our projects we use `wherePivot` in some cases and they appear to be flagged as "Dynamic method call"

`Dynamic where method 'wherePivot' should not be used.`

While wherePivot is an actual method and not a dynamic call.

I'll give it another look later but first clue would be this [method](https://github.com/canvural/larastan-strict-rules/blob/514867225ca3a196706cb5dfe0002aec61e0114f/src/Rules/NoDynamicWhereRule.php#L127)

**Comment by canvural** [comment]
Hi,

Looks like `wherePivot` is coming from `BelongsToMany` class. So I think `BelongsToMany` should be added to the condition here also: https://github.com/canvural/larastan-strict-rules/blob/514867225ca3a196706cb5dfe0002aec61e0114f/src/Rules/NoDynamicWhereRule.php#L103-L107

You can create a PR with that change and also add a test case here: https://github.com/canvural/larastan-strict-rules/blob/master/tests/Rules/data/dynamic-where.php

**Comment by canvural** [comment]
And I suppose same applies to other methods like `wherePivotNotIn`, `wherePivotIn` etc. Please include them in the test cases.

**Comment by jeremynikolic** [comment]
Nice thanks for the directions, I'll have a look 👍

**Comment by jeremynikolic** [comment]
[PR submitted](https://github.com/canvural/larastan-strict-rules/pull/92) 

Let me know if I should adjust parts of the testing 😄

**Comment by canvural** [comment]
Fixed by https://github.com/canvural/larastan-strict-rules/pull/92

**Comment by canvural** [comment]
Released in https://github.com/canvural/larastan-strict-rules/releases/tag/v2.1.3 Please test it 👍🏽

**Comment by jeremynikolic** [comment]
Will do and let you know 👍
